FORMAT: 1A
HOST: http://utilify.io/

# utilify

API to discover utility bills information.

## Providers [/providers]

### Get all Providers [GET]

+ Response 200 (application/json)

    + Body

            [
                {
                    "id": "1234",
                    "name": "Provider Name Ltd"
                },
                {
                    "id": "2345",
                    "name": "Some other provider Ltd",
                }
            ]

## Utility [/utility]

### Scrape for a new utility [POST]

+ Request

    + Body
          {
            "firstname": "Joe",
            "lastname": "Doe",
            "address": "6 Nowhere Close, Nowherenear, Nowherenearshire, N01 0PE"
          }

+ Response 201 (application/json)

    + Headers

            Location: /utility/1
    + Body

            {
              "id": 1,
              "createdAt": "2016-04-23T18:25:43.511Z",
              "firstname": "Joe",
              "middlename": "",
              "lastname": "Doe",
              "address": {
                "line1": "6 Nowhere Close",
                "line2": "",
                "line3": "",
                "line4": "",
                "city": "Nowherenear",
                "county": "Nowherenearshire",
                "postcode": "N01 0PE",
                "country": "UK"
              }
            }
