FORMAT: 1A
HOST: http://api.utilify.io/

# utilify

API to discover utility bills information.

## Providers [/providers]
List of providers that Utilify can extract information

### Get a list of available Providers [GET]
Retrieve list

+ Response 200 (application/json)

    + Body

            [
                {
                    "id": "1234",
                    "name": "Provider Name Ltd",
                    "link": "https://utlify.io/providers/provider-name",
                    "status": "online"
                },
                {
                    "id": "2345",
                    "name": "Some other provider Ltd",
                    "link": "https://utilify.io/providers/some-other-provider",
                    "status": "offline"
                }
            ]

## Utility [/utility]
Utility contains account details extracted from provider's website

### Scrape provider for utility details [POST]
Posting user's login details for specific providers initiates data extraction

+ Request (application/json)

    + Body
    
            {
                "providerId": "someproviderid"
                "providerLoginDetails":{
                    "username": "joedoe",
                    "password": "superduperlongdifficultpassword"
                }
            }

+ Response 202 (application/json)

    + Headers

            Location: /utility/e10ac2cd-f9e9-4215-9ee1-feac80ba4f92
    + Body

            {
              "id": "e10ac2cd-f9e9-4215-9ee1-feac80ba4f92",
              "createdAt": "2016-04-23T18:25:43.511Z",
              "link": "https://utlify.io/utlity/e10ac2cd-f9e9-4215-9ee1-feac80ba4f92"
            }
            



### Get utility details [GET /utility/{id}]
Retrieve utility account details extracted from provider's website.

+ Parameters 
    + id (uuid) - Id reference for the utility details
    
+ Response 200 (application/json)
    
    + Body
    
            {
                "providerId": "someOtherProviderId",
                "customerName": {
                    "firstName": "Nope",
                    "middleName": "NotMe",
                    "lastName": "Noone"
                },
                "customerAddress": {
                    "line1": "6 Nowhere Close",
                    "line2": "",
                    "line3": "",
                    "line4": "",
                    "city": "Nowhere",
                    "county": "NowhereShire",
                    "postcode": "N00 0PE",
                    "country": "UK"
                },
                "accountReference": "someUniqueAccountReference",
                "documentLink": "https://utilify.io/utility/file/someUniqueDocumentId",
                "lastPaymentAt": "2016-01-01T12:00:00.000Z"
            }

## Account [/account]
Account holds information about user account with the provider

### Account balance [GET /account/balance]
Retrieve account balance

+ Response 200 (application/json)

    + Body
    
            {
                "money": {
                    "amount": 100.50,
                    "currency": "GBP"
                }
            }